// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: object.proto
#ifndef GRPC_object_2eproto__INCLUDED
#define GRPC_object_2eproto__INCLUDED

#include "object.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vfs {

class NameService final {
 public:
  static constexpr char const* service_full_name() {
    return "vfs.NameService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::vfs::ABObject>> ListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::vfs::ABObject>>(ListDirectoryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::vfs::ABObject>> AsyncListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::vfs::ABObject>>(AsyncListDirectoryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::vfs::ABObject>> PrepareAsyncListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::vfs::ABObject>>(PrepareAsyncListDirectoryRaw(context, request, cq));
    }
    virtual ::grpc::Status FindObject(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::vfs::ABObject* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vfs::ABObject>> AsyncFindObject(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vfs::ABObject>>(AsyncFindObjectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vfs::ABObject>> PrepareAsyncFindObject(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vfs::ABObject>>(PrepareAsyncFindObjectRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest* request, ::grpc::ClientReadReactor< ::vfs::ABObject>* reactor) = 0;
      virtual void FindObject(::grpc::ClientContext* context, const ::vfs::PathRequest* request, ::vfs::ABObject* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FindObject(::grpc::ClientContext* context, const ::vfs::PathRequest* request, ::vfs::ABObject* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::vfs::ABObject>* ListDirectoryRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::vfs::ABObject>* AsyncListDirectoryRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::vfs::ABObject>* PrepareAsyncListDirectoryRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vfs::ABObject>* AsyncFindObjectRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vfs::ABObject>* PrepareAsyncFindObjectRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::vfs::ABObject>> ListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::vfs::ABObject>>(ListDirectoryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::vfs::ABObject>> AsyncListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::vfs::ABObject>>(AsyncListDirectoryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::vfs::ABObject>> PrepareAsyncListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::vfs::ABObject>>(PrepareAsyncListDirectoryRaw(context, request, cq));
    }
    ::grpc::Status FindObject(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::vfs::ABObject* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vfs::ABObject>> AsyncFindObject(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vfs::ABObject>>(AsyncFindObjectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vfs::ABObject>> PrepareAsyncFindObject(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vfs::ABObject>>(PrepareAsyncFindObjectRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListDirectory(::grpc::ClientContext* context, const ::vfs::PathRequest* request, ::grpc::ClientReadReactor< ::vfs::ABObject>* reactor) override;
      void FindObject(::grpc::ClientContext* context, const ::vfs::PathRequest* request, ::vfs::ABObject* response, std::function<void(::grpc::Status)>) override;
      void FindObject(::grpc::ClientContext* context, const ::vfs::PathRequest* request, ::vfs::ABObject* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::vfs::ABObject>* ListDirectoryRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request) override;
    ::grpc::ClientAsyncReader< ::vfs::ABObject>* AsyncListDirectoryRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::vfs::ABObject>* PrepareAsyncListDirectoryRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vfs::ABObject>* AsyncFindObjectRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vfs::ABObject>* PrepareAsyncFindObjectRaw(::grpc::ClientContext* context, const ::vfs::PathRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListDirectory_;
    const ::grpc::internal::RpcMethod rpcmethod_FindObject_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ListDirectory(::grpc::ServerContext* context, const ::vfs::PathRequest* request, ::grpc::ServerWriter< ::vfs::ABObject>* writer);
    virtual ::grpc::Status FindObject(::grpc::ServerContext* context, const ::vfs::PathRequest* request, ::vfs::ABObject* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListDirectory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListDirectory() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListDirectory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDirectory(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::grpc::ServerWriter< ::vfs::ABObject>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListDirectory(::grpc::ServerContext* context, ::vfs::PathRequest* request, ::grpc::ServerAsyncWriter< ::vfs::ABObject>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FindObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FindObject() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FindObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindObject(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::vfs::ABObject* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindObject(::grpc::ServerContext* context, ::vfs::PathRequest* request, ::grpc::ServerAsyncResponseWriter< ::vfs::ABObject>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListDirectory<WithAsyncMethod_FindObject<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListDirectory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListDirectory() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::vfs::PathRequest, ::vfs::ABObject>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vfs::PathRequest* request) { return this->ListDirectory(context, request); }));
    }
    ~WithCallbackMethod_ListDirectory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDirectory(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::grpc::ServerWriter< ::vfs::ABObject>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::vfs::ABObject>* ListDirectory(
      ::grpc::CallbackServerContext* /*context*/, const ::vfs::PathRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FindObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FindObject() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::vfs::PathRequest, ::vfs::ABObject>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vfs::PathRequest* request, ::vfs::ABObject* response) { return this->FindObject(context, request, response); }));}
    void SetMessageAllocatorFor_FindObject(
        ::grpc::MessageAllocator< ::vfs::PathRequest, ::vfs::ABObject>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vfs::PathRequest, ::vfs::ABObject>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FindObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindObject(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::vfs::ABObject* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindObject(
      ::grpc::CallbackServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::vfs::ABObject* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListDirectory<WithCallbackMethod_FindObject<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListDirectory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListDirectory() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListDirectory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDirectory(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::grpc::ServerWriter< ::vfs::ABObject>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FindObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FindObject() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FindObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindObject(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::vfs::ABObject* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListDirectory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListDirectory() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListDirectory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDirectory(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::grpc::ServerWriter< ::vfs::ABObject>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListDirectory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FindObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FindObject() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FindObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindObject(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::vfs::ABObject* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindObject(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListDirectory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListDirectory() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->ListDirectory(context, request); }));
    }
    ~WithRawCallbackMethod_ListDirectory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDirectory(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::grpc::ServerWriter< ::vfs::ABObject>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ListDirectory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FindObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FindObject() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FindObject(context, request, response); }));
    }
    ~WithRawCallbackMethod_FindObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindObject(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::vfs::ABObject* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindObject(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FindObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FindObject() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vfs::PathRequest, ::vfs::ABObject>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vfs::PathRequest, ::vfs::ABObject>* streamer) {
                       return this->StreamedFindObject(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FindObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FindObject(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::vfs::ABObject* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFindObject(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vfs::PathRequest,::vfs::ABObject>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FindObject<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ListDirectory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ListDirectory() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::vfs::PathRequest, ::vfs::ABObject>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::vfs::PathRequest, ::vfs::ABObject>* streamer) {
                       return this->StreamedListDirectory(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ListDirectory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListDirectory(::grpc::ServerContext* /*context*/, const ::vfs::PathRequest* /*request*/, ::grpc::ServerWriter< ::vfs::ABObject>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedListDirectory(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::vfs::PathRequest,::vfs::ABObject>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ListDirectory<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_ListDirectory<WithStreamedUnaryMethod_FindObject<Service > > StreamedService;
};

}  // namespace vfs


#endif  // GRPC_object_2eproto__INCLUDED
